// Embedding-based blending for primer / best-practice suggestion.
//
// The canonical matcher (src/primers/match.ts) uses weighted Jaccard on
// tech/lens tags. This module adds an optional second signal: cosine
// similarity between a query embedding and precomputed entry embeddings,
// blended with the tag score via a configurable weight.
//
// Design:
//   - Vectors are precomputed by `vcf embed-kb`, not fetched at query time.
//     The query text (usually tag join) is embedded live — one call per
//     suggest.
//   - Cache misses fall back to tag-only for *that* entry, not the whole
//     query. A partially-embedded KB still benefits from embeddings where
//     available.
//   - Cosine of a missing vector is treated as 0, never as a negative
//     penalty — so adding embeddings can only improve ordering.

import { readFile, readdir, stat, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { createHash } from "node:crypto";

/** On-disk shape of a single cached vector file. */
export interface EmbeddingRecord {
  model: string;
  dim: number;
  content_sha256: string;
  vector: number[];
  updated_at: number;
}

export interface EmbeddingCache {
  /** entry.id → vector (null when mismatch / corrupt / missing) */
  byId: Map<string, number[]>;
  model: string | null;
  dim: number | null;
}

/** Cosine similarity. Returns 0 when either side is zero-length or dim mismatch. */
export function cosine(a: readonly number[], b: readonly number[]): number {
  if (a.length === 0 || a.length !== b.length) return 0;
  let dot = 0;
  let na = 0;
  let nb = 0;
  for (let i = 0; i < a.length; i++) {
    const x = a[i]!;
    const y = b[i]!;
    dot += x * y;
    na += x * x;
    nb += y * y;
  }
  if (na === 0 || nb === 0) return 0;
  return dot / (Math.sqrt(na) * Math.sqrt(nb));
}

/**
 * Normalize a tag-Jaccard score (already in [0, primary_weight*k]) into [0,1]
 * for blending against cosine. `denom` is the max score observed among
 * candidates so the relative ordering of tag-only items is preserved.
 */
export function normalizeTagScore(raw: number, maxSeen: number): number {
  if (maxSeen <= 0) return 0;
  return raw / maxSeen;
}

export function blend(tagNormalized: number, cosineScore: number, weight: number): number {
  const w = Math.min(1, Math.max(0, weight));
  return w * cosineScore + (1 - w) * tagNormalized;
}

export function sha256(s: string): string {
  return createHash("sha256").update(s).digest("hex");
}

/**
 * Default cache root honors config.embeddings.cache_dir; otherwise
 * ~/.vcf/embeddings/.
 */
export function defaultCacheDir(homedir: string, override: string | undefined): string {
  return override ?? join(homedir, ".vcf", "embeddings");
}

/**
 * Load every embedding record under `cacheDir`. Records whose `model` does
 * not match `expectedModel` are dropped from the returned map (they'll be
 * regenerated by the next `vcf embed-kb`).
 */
export async function loadEmbeddingCache(
  cacheDir: string,
  expectedModel: string,
): Promise<EmbeddingCache> {
  const result: EmbeddingCache = { byId: new Map(), model: null, dim: null };
  if (!existsSync(cacheDir)) return result;

  const stack: string[] = [cacheDir];
  while (stack.length > 0) {
    const dir = stack.pop()!;
    let names: string[];
    try {
      names = await readdir(dir);
    } catch {
      continue;
    }
    for (const name of names) {
      const full = join(dir, name);
      const st = await stat(full).catch(() => null);
      if (!st) continue;
      if (st.isDirectory()) {
        stack.push(full);
        continue;
      }
      if (!name.endsWith(".json")) continue;
      try {
        const raw = await readFile(full, "utf8");
        const rec = JSON.parse(raw) as EmbeddingRecord;
        if (rec.model !== expectedModel) continue;
        if (!Array.isArray(rec.vector) || rec.vector.length === 0) continue;
        // id = path relative to cacheDir, minus the .json extension, using
        // forward slashes so it matches KbEntry.id on all platforms.
        const relPath = full.slice(cacheDir.length + 1).replace(/\\/g, "/");
        const id = relPath.replace(/\.json$/, "");
        result.byId.set(id, rec.vector);
        if (result.model === null) result.model = rec.model;
        if (result.dim === null) result.dim = rec.dim;
      } catch {
        // Skip unreadable entries; next embed-kb run will regenerate.
      }
    }
  }
  return result;
}

export async function writeEmbeddingRecord(
  cacheDir: string,
  id: string,
  rec: EmbeddingRecord,
): Promise<void> {
  const target = join(cacheDir, `${id}.json`);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, JSON.stringify(rec, null, 2) + "\n", "utf8");
}

/**
 * Build the text that represents a KB entry for embedding. Uses frontmatter
 * name + tags + first ~2000 chars of body for a stable, cost-bounded input.
 */
export function buildEmbeddingInput(
  entry: { name: string; tags: readonly string[]; applies_to: readonly string[] },
  body: string,
): string {
  const header = [entry.name, entry.tags.join(" "), entry.applies_to.join(" ")].join(" ").trim();
  const trimmed = body.replace(/\s+/g, " ").trim().slice(0, 2000);
  return `${header}\n\n${trimmed}`;
}
